version: 2.0

# heavily inspired by https://raw.githubusercontent.com/pinax/pinax-wiki/6bd2a99ab6f702e300d708532a6d1d9aa638b9f8/.circleci/config.yml

common: &common
  working_directory: ~/repo
  steps:
    - checkout
    - run:
        name: merge pull request base
        command: ./.circleci/merge_pr.sh
    - run:
        name: merge pull request base (2nd try)
        command: ./.circleci/merge_pr.sh
        when: on_fail
    - run:
        name: merge pull request base (3nd try)
        command: ./.circleci/merge_pr.sh
        when: on_fail
    - restore_cache:
        keys:
          - v6-cache-{{ .Environment.CIRCLE_JOB }}-{{ checksum "setup.py" }}-{{ checksum "tox.ini" }}
    - run:
        name: install dependencies
        command: pip install --user tox
    - run:
        name: run tox
        command: ~/.local/bin/tox -r
    - save_cache:
        paths:
          - .hypothesis
          - .tox
          - ~/.cache/pip
          - ~/.local
          - ./eggs
        key: v6-cache-{{ .Environment.CIRCLE_JOB }}-{{ checksum "setup.py" }}-{{ checksum "tox.ini" }}

jobs:
  docs:
    <<: *common
    docker:
      - image: circleci/python:3.7
        environment:
          TOXENV: docs
  django20:
    <<: *common
    docker:
      - image: circleci/python:3.6
        environment:
          TOXENV: 'py36-django20-drf{38,39}-tests'
  django21:
    <<: *common
    docker:
      - image: circleci/python:3.7
        environment:
          TOXENV: 'py37-django21-drf{39,310}-tests'
  django22:
    <<: *common
    docker:
      - image: circleci/python:3.7
        environment:
          TOXENV: 'py37-django22-drf{39,310,311}-tests'
  django30:
    <<: *common
    docker:
      - image: circleci/python:3.8
        environment:
          TOXENV: 'py38-django30-drf{310,311}-tests'
  djangomaster:
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: merge pull request base
          command: ./.circleci/merge_pr.sh
      - run:
          name: merge pull request base (2nd try)
          command: ./.circleci/merge_pr.sh
          when: on_fail
      - run:
          name: merge pull request base (3nd try)
          command: ./.circleci/merge_pr.sh
          when: on_fail
      - restore_cache:
          keys:
            - v6-cache-{{ .Environment.CIRCLE_JOB }}-{{ checksum "setup.py" }}-{{ checksum "tox.ini" }}
      - run:
          name: install dependencies
          command: pip install --user tox
      - run:
          name: run tox
          # Allow failures for django master tests
          command: ~/.local/bin/tox -r || true
      - save_cache:
          paths:
            - .hypothesis
            - .tox
            - ~/.cache/pip
            - ~/.local
            - ./eggs
          key: v6-cache-{{ .Environment.CIRCLE_JOB }}-{{ checksum "setup.py" }}-{{ checksum "tox.ini" }}
    docker:
      - image: circleci/python:3.8
        environment:
          TOXENV: 'py38-djangomaster-drf310-tests'
  lint:
    <<: *common
    docker:
      - image: circleci/python:3.7
        environment:
          TOXENV: lint

workflows:
  version: 2
  test:
    jobs:
      - docs
      - django20
      - django21
      - django22
      - django30
      - djangomaster
      - lint
